export type CurrencyType = {
  value: string
  label: string
  symbol: string
  locale: string
  groupSep: string
  decSep: string
}

export const currencies: CurrencyType[] = [
  {
    value: 'DZD',
    label: 'Algerian Dinar (د.ج)',
    symbol: 'د.ج',
    locale: 'ar-DZ',
    decSep: ',',
    groupSep: '.',
  },
  {
    value: 'ARS',
    label: 'Argentine Peso ($)',
    symbol: '$',
    locale: 'es-AR',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'AUD',
    label: 'Australian Dollar ($)',
    symbol: '$',
    locale: 'en-AU',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'BHD',
    label: 'Bahraini Dinar (BHD)',
    symbol: 'BHD',
    locale: 'en-BH',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'BDT',
    label: 'Bangladeshi Taka (৳)',
    symbol: '৳',
    locale: 'bn-BD',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'BRL',
    label: 'Brazilian Real (R$)',
    symbol: '$',
    locale: 'pt-BR',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'GBP',
    label: 'British Pound (£)',
    symbol: '£',
    locale: 'en-GB',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'CAD',
    label: 'Canadian Dollar ($)',
    symbol: '$',
    locale: 'en-CA',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'XAF',
    label: 'Central African CFA Franc (FCFA)',
    symbol: 'FCFA',
    locale: 'fr-CM',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'CLP',
    label: 'Chilean Peso ($)',
    symbol: '$',
    locale: 'es-CL',
    groupSep: '.',
    decSep: '',
  },
  {
    value: 'CNY',
    label: 'Chinese Yuan (¥)',
    symbol: '¥',
    locale: 'zh-CN',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'COP',
    label: 'Colombian Peso ($)',
    symbol: '$',
    locale: 'es-CO',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'CDF',
    label: 'Congolese Franc (FC)',
    symbol: 'FC',
    locale: 'fr-CD',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'EGP',
    label: 'Egyptian Pound (EGP)',
    symbol: 'EGP',
    locale: 'en-EG',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'ETB',
    label: 'Ethiopian Birr (Br)',
    symbol: 'Br',
    locale: 'am-ET',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'EUR',
    label: 'Euro (€)',
    symbol: '€',
    locale: 'de-DE',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'GHS',
    label: 'Ghanaian Cedi (GH₵)',
    symbol: 'GH₵',
    locale: 'en-GH',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'HKD',
    label: 'Hong Kong Dollar (HK$)',
    symbol: 'HK$',
    locale: 'zh-HK',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'INR',
    label: 'Indian Rupee (₹)',
    symbol: '₹',
    locale: 'hi-IN',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'IDR',
    label: 'Indonesian Rupiah (Rp)',
    symbol: 'Rp',
    locale: 'id-ID',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'IQD',
    label: 'Iraqi Dinar (IQD)',
    symbol: 'IQD',
    locale: 'en-IQ',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'JPY',
    label: 'Japanese Yen (¥)',
    symbol: '¥',
    locale: 'ja-JP',
    groupSep: ',',
    decSep: '',
  },
  {
    value: 'KZT',
    label: 'Kazakhstani Tenge (₸)',
    symbol: '₸',
    locale: 'kk-KZ',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'KES',
    label: 'Kenyan Shilling (KSh)',
    symbol: 'KSh',
    locale: 'sw-KE',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'KWD',
    label: 'Kuwaiti Dinar (KWD)',
    symbol: 'KWD',
    locale: 'en-KW',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'LBP',
    label: 'Lebanese Pound (LBP)',
    symbol: 'LBP',
    locale: 'en-LB',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'MYR',
    label: 'Malaysian Ringgit (RM)',
    symbol: 'RM',
    locale: 'ms-MY',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'MXN',
    label: 'Mexican Peso ($)',
    symbol: '$',
    locale: 'es-MX',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'MAD',
    label: 'Moroccan Dirham (د.م.)',
    symbol: 'د.م.',
    locale: 'ar-MA',
    groupSep: '٬',
    decSep: '٫',
  },
  {
    value: 'MZN',
    label: 'Mozambican Metical (MTn)',
    symbol: 'MTn',
    locale: 'pt-MZ',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'NZD',
    label: 'New Zealand Dollar ($)',
    symbol: '$',
    locale: 'en-NZ',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'NGN',
    label: 'Nigerian Naira (₦)',
    symbol: '₦',
    locale: 'en-NG',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'NOK',
    label: 'Norwegian Krone (kr)',
    symbol: 'kr',
    locale: 'nb-NO',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'OMR',
    label: 'Omani Rial (﷼)',
    symbol: '﷼',
    locale: 'en-OM',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'PKR',
    label: 'Pakistani Rupee (₨)',
    symbol: '₨',
    locale: 'ur-PK',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'PHP',
    label: 'Philippine Peso (₱)',
    symbol: '₱',
    locale: 'tl-PH',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'QAR',
    label: 'Qatari Riyal (ر.ق)',
    symbol: 'ر.ق',
    locale: 'en-QA',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'RUB',
    label: 'Russian Ruble (₽)',
    symbol: '₽',
    locale: 'ru-RU',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'SAR',
    label: 'Saudi Riyal (﷼)',
    symbol: '﷼',
    locale: 'en-SA',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'SGD',
    label: 'Singapore Dollar ($)',
    symbol: '$',
    locale: 'en-SG',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'ZAR',
    label: 'South African Rand (R)',
    symbol: 'R',
    locale: 'en-ZA',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'KRW',
    label: 'South Korean Won (₩)',
    symbol: '₩',
    locale: 'ko-KR',
    groupSep: ',',
    decSep: '',
  },
  {
    value: 'SDG',
    label: 'Sudanese Pound (ج.س)',
    symbol: 'ج.س',
    locale: 'en-SD',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'SEK',
    label: 'Swedish Krona (kr)',
    symbol: 'kr',
    locale: 'sv-SE',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'CHF',
    label: 'Swiss Franc (CHF)',
    symbol: 'CHF',
    locale: 'fr-CH',
    groupSep: "'",
    decSep: '.',
  },
  {
    value: 'TZS',
    label: 'Tanzanian Shilling (TSh)',
    symbol: 'TSh',
    locale: 'sw-TZ',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'THB',
    label: 'Thai Baht (฿)',
    symbol: '฿',
    locale: 'th-TH',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'TRY',
    label: 'Turkish Lira (₺)',
    symbol: '₺',
    locale: 'tr-TR',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'AED',
    label: 'UAE Dirham (د.إ)',
    symbol: 'د.إ',
    locale: 'ar-AE',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'UGX',
    label: 'Ugandan Shilling (USh)',
    symbol: 'USh',
    locale: 'sw-UG',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'UAH',
    label: 'Ukrainian Hryvnia (₴)',
    symbol: '₴',
    locale: 'uk-UA',
    groupSep: ' ',
    decSep: ',',
  },
  {
    value: 'USD',
    label: 'US Dollar ($)',
    symbol: '$',
    locale: 'en-US',
    groupSep: ',',
    decSep: '.',
  },
  {
    value: 'VND',
    label: 'Vietnamese Dong (₫)',
    symbol: '₫',
    locale: 'vi-VN',
    groupSep: '.',
    decSep: ',',
  },
  {
    value: 'XOF',
    label: 'West African CFA Franc (F CFA)',
    symbol: 'F CFA',
    locale: 'fr-BJ',
    groupSep: ' ',
    decSep: ',',
  },
]

export const defaultCurrency = currencies.find(c => c.value === 'USD') || currencies[0]

export type LanguageType = {
  value: string
  label: string
  alternative: string
}

export const languages: LanguageType[] = [
  { value: 'en', label: 'English', alternative: 'English' },
  { value: 'zh', label: '简体中文', alternative: 'Chinese (Simplified)' },
  { value: 'zh-Hant', label: '繁體中文', alternative: 'Chinese (Traditional)' },
  { value: 'hi', label: 'हिन्दी', alternative: 'Hindi' },
  { value: 'es', label: 'Español', alternative: 'Spanish' },
  { value: 'ar', label: 'العربية', alternative: 'Arabic' },
  { value: 'bn', label: 'বাংলা', alternative: 'Bengali' },
  { value: 'pt', label: 'Português', alternative: 'Portuguese' },
  { value: 'ru', label: 'Русский', alternative: 'Russian' },
  { value: 'ur', label: 'اردو', alternative: 'Urdu' },
  { value: 'id', label: 'Bahasa Indonesia', alternative: 'Indonesian' },
  { value: 'de', label: 'Deutsch', alternative: 'German' },
  { value: 'ja', label: '日本語', alternative: 'Japanese' },
  { value: 'fr', label: 'Français', alternative: 'French' },
  { value: 'te', label: 'తెలుగు', alternative: 'Telugu' },
  { value: 'ta', label: 'தமிழ்', alternative: 'Tamil' },
  { value: 'ko', label: '한국어', alternative: 'Korean' },
  { value: 'tr', label: 'Türkçe', alternative: 'Turkish' },
  { value: 'ml', label: 'മലയാളം', alternative: 'Malayalam' },
  { value: 'vi', label: 'Tiếng Việt', alternative: 'Vietnamese' },
  { value: 'it', label: 'Italiano', alternative: 'Italian' },
  { value: 'th', label: 'ไทย', alternative: 'Thai' },
  { value: 'gu', label: 'ગુજરાતી', alternative: 'Gujarati' },
  { value: 'kn', label: 'ಕನ್ನಡ', alternative: 'Kannada' },
  { value: 'ms', label: 'Bahasa Melayu', alternative: 'Malay' },
  { value: 'nl', label: 'Nederlands', alternative: 'Dutch' },
]

export const defaultLanguage = languages.find(l => l.value === 'en') || languages[0]
